### ISSUE TITLE
Data is not efficient!  (simulation issue)

### ISSUE THREAD

**Issue by CAI23sbP** [Arena-Rosnav/arena-rosnav#44]
Hi @ReykCS. I solved last issue by my self.
I have a new issue about simulation.
It is that a episode's time step is too short to achieve a agent's goal. it means that most of episodes have info as timeout!. As a result, the agent is not learning a policy which is take a goal! 
Briefly speaking "Your default maximum time step in single episode is 250, it doesn't helpful to learning."  
I wish that this issue will be helpful your project thank you!

**Comment by ReykCS** [comment]
Hey @CAI23sbP ,

i think instead of simulation you mean the actual training, because the timeout in the simulation is set to a specific time value, which is 3 minutes by default.
But you are completely right, in the default training config file we set the maximal number episodes to be 250. But to be really honest with you, i was not responsible for this part of the code and i dont know why this value was chosen. I think we tried around with some different values and finally converged at the current default. Too high values cause episodes to take very long and the actual adaption step is then performed only very sporadically, which causes the network to learn only very slowly. Too short episode length cause the simulation to quit way to early and oftentime the agent cannot archieve any positiv rewards in this time, which also causes very long learning times. I am very sure that @tuananhroman can say way more to this and explain you in detail why we ultimately chose this value.

**Comment by CAI23sbP** [comment]
Oh thank you for your quickly response @ReykCS .
I understood why we need to setting about max time step. but i mean that we need to setting a valid goal position.  
when i launched training code by setting a DWA(local planner algorithm) robot without backward. robot could not achieve its goal which was so far way from the robot (ex: a diagonal position from robot to goal in empty map).
So my opinion is that we need to create a valid goal position (still in random but not so far away from the robot. At least the robot can take its goal) to make more efficient data.

**Comment by ReykCS** [comment]
Hey @CAI23sbP ,

it definitely makes sense in general to set a random distance between the goal and the start position. However, this might vary and is strongly depending on the map one is using, so hardcoding this value would not be an option. 
Additionally, in general, it is not really necessary for the robot to really reach the goal. We want to provide a framework for benchmarking and training different navigational algorithms and therefore it is not necessary to always provide solvable tasks. This only holds as long as one wants to compare different algorithms and runs. 
For the training, it is neither necessary that the robot reaches the goal in every run, as the approach to the goal is also beneficial for the training. 
When one really wants to analyze specific runs, planners, and robots, one should anyways create a custom scenario file in which a timeout can be established as well. 

So in general: It is definitely an issue for some planners in combination with some maps but I don't think that changing the position generation is the perfect place to fix this issue. Instead of this, one should change the timeout itself in the constant file or with creating custom scenario files.
